events {}

http {
    upstream api_gateway_cluster {
        server api_gateway:5000;  # Docker auto-discovers all api_gateway replicas!
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_gateway_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
